backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Beiträge"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Entwurf", name: "draft", widget: "boolean", default: true }
      - { label: "Tags", name: "tags", widget: "list", default: [] }
      - { label: "Inhalt", name: "body", widget: "markdown" }
